// PANews 工具数据 - 完整提取
// 从 https://www.panewslab.com/zh/tools 抓取

export const panewsTools = [
  // ===== 热门 =====
  {
    name: '推特KOL列表',
    description: '推荐关注的Twitter账号',
    icon: 'https://cdn-img.panewslab.com/panews/2022/11/03/images/x6w7EVx1B7.jpg',
    url: 'https://x.com/list',
    category: '热门',
    tags: ['Social', 'Twitter', 'KOL'],
  },
  {
    name: 'GMGN.Ai',
    description: 'MEME交易终端',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/31/images/88UOLYaJub.jpg',
    url: 'https://gmgn.ai',
    category: '热门',
    tags: ['Trading', 'Meme', 'Solana'],
    hot: true,
  },
  {
    name: 'Etherscan',
    description: '以太坊区块链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/ayT98NBf91.png',
    url: 'https://etherscan.io',
    category: '热门',
    tags: ['Explorer', 'Ethereum'],
    hot: true,
  },
  {
    name: 'MetaMask',
    description: 'Web3钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/E5X632ipfa.jpg',
    url: 'https://metamask.io',
    category: '热门',
    tags: ['Wallet', 'Web3', 'Ethereum'],
    hot: true,
  },
  {
    name: 'DeFi Llama',
    description: '全链DeFi数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/3Pdl99fm2l.jpg',
    url: 'https://defillama.com',
    category: '热门',
    tags: ['DeFi', 'Data', 'TVL'],
    hot: true,
  },
  {
    name: 'CoinMarketCap',
    description: '行情数据网站',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/6Jhr4Tj8Wf.jpg',
    url: 'https://coinmarketcap.com',
    category: '热门',
    tags: ['Price', 'Market', 'Data'],
    hot: true,
  },
  {
    name: 'Dune',
    description: '综合链上数据分析',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/8y6TB3Zj0X.png',
    url: 'https://dune.com',
    category: '热门',
    tags: ['Analytics', 'Data', 'SQL'],
    hot: true,
  },
  {
    name: 'Debank',
    description: '加密投资组合追踪',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/n8I70y0IoQ.jpg',
    url: 'https://debank.com',
    category: '热门',
    tags: ['Portfolio', 'Wallet', 'DeFi'],
    hot: true,
  },
  {
    name: 'Zcash Dashboard',
    description: 'Zcash 数据看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/11/17/images/u17A3qrWP5.jpg',
    url: 'https://zcashteam.com',
    category: '热门',
    tags: ['Analytics', 'Zcash'],
  },
  {
    name: 'CoinGecko',
    description: '行情数据网站',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/XB7R5bWg0E.jpg',
    url: 'https://coingecko.com',
    category: '热门',
    tags: ['Price', 'Market', 'Data'],
    hot: true,
  },
  {
    name: 'Ultra Sound Money',
    description: '以太坊供应数据监测',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/26/images/yrVo905PFl.jpg',
    url: 'https://ultrasound.money',
    category: '热门',
    tags: ['Ethereum', 'Analytics', 'Burn'],
  },
  {
    name: '恐惧与贪婪指数',
    description: '恐惧与贪婪指数查询',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/H7hV5l7AC4.jpg',
    url: 'https://alternative.me/crypto/fear-and-greed-index/',
    category: '热门',
    tags: ['Sentiment', 'Index'],
  },
  {
    name: 'TradingView',
    description: '专业行情分析工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/CJvbdMxnwQ.jpg',
    url: 'https://tradingview.com',
    category: '热门',
    tags: ['Charts', 'Trading', 'Technical'],
  },
  {
    name: 'growthepie',
    description: '以太坊生态数据看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/07/11/images/M442c3uPlT.jpg',
    url: 'https://growthepie.xyz',
    category: '热门',
    tags: ['Ethereum', 'Analytics', 'L2'],
  },
  {
    name: 'Nansen',
    description: '交易所钱包余额',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/g3Fsmv91mZ.png',
    url: 'https://www.nansen.ai',
    category: '热门',
    tags: ['Analytics', 'Wallet', 'On-chain'],
  },
  {
    name: 'Blockworks',
    description: '加密财库公司综合看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/QA4j9wJ7ka.jpg',
    url: 'https://www.coincenter.io/treasury',
    category: '热门',
    tags: ['Treasury', 'Data'],
  },
  {
    name: 'DELPHI DIGITAL',
    description: '加密财库公司综合看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/FkdBUs52Vx.jpg',
    url: 'https://delphidigital.io',
    category: '热门',
    tags: ['Research', 'Data'],
  },
  {
    name: 'THE BLOCK',
    description: '加密财库公司综合看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/8cIvwE45Ym.jpg',
    url: 'https://www.theblock.co',
    category: '热门',
    tags: ['Research', 'Data'],
  },
  {
    name: 'Crypto Stock Tracker',
    description: '加密财库公司综合看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/2QY8o9137F.jpg',
    url: 'https://cryptostockertracker.com',
    category: '热门',
    tags: ['Stock', 'Crypto'],
  },
  {
    name: 'Crypto Treasuries',
    description: '加密财库公司综合看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/Di5P2Jj41K.png',
    url: 'https://cryptotreasury.xyz',
    category: '热门',
    tags: ['Treasury', 'Data'],
  },
  {
    name: 'Bitcoin Treasuries',
    description: '上市公司BTC财库看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/2hD608X4Ia.jpg',
    url: 'https://bitcointreasuries.net',
    category: '热门',
    tags: ['Bitcoin', 'Treasury', 'Corporate'],
  },
  {
    name: 'CompaniesMarketCap',
    description: 'BTC持有量排行（公司市值）',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/ira73Q24s7.jpg',
    url: 'https://companiesmarketcap.com',
    category: '热门',
    tags: ['Corporate', 'Bitcoin', 'Data'],
  },
  {
    name: 'SoSoValue',
    description: '上市公司BTC财库看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/x6yvkAO2DK.jpg',
    url: 'https://www.sosovalue.com',
    category: '热门',
    tags: ['Bitcoin', 'Treasury', 'Analytics'],
  },
  {
    name: 'bitbo',
    description: '上市公司BTC财库看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/10UMHXMrR1.jpg',
    url: 'https://bitbo.io',
    category: '热门',
    tags: ['Bitcoin', 'Analytics', 'Data'],
  },
  {
    name: 'newhedge',
    description: '公司BTC财库看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/75Ioe1ZVAG.jpg',
    url: 'https://newhedge.io',
    category: '热门',
    tags: ['Bitcoin', 'Treasury'],
  },
  {
    name: 'Strategic ETH Reserve',
    description: 'ETH战略储备看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/82y3eWv9No.png',
    url: 'https://www.ststrategic.io',
    category: '热门',
    tags: ['Ethereum', 'Treasury'],
  },
  {
    name: 'Finder',
    description: 'ETH财库看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/01/images/GBfM0VGGcr.jpg',
    url: 'https://www.finder.com',
    category: '热门',
    tags: ['Ethereum', 'Treasury'],
  },
  {
    name: 'BBX',
    description: '加密货币储备综合看板',
    icon: 'https://cdn-img.panewslab.com/panews/2025/08/04/images/1McDEzrNLq.jpg',
    url: 'https://bbx.finance',
    category: '热门',
    tags: ['Treasury', 'Multi-chain'],
  },

  // ===== AI Agent =====
  {
    name: 'Act I : The AI Prophecy',
    description: 'AI 交互协作平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/139FcF16Ws.jpg',
    url: 'https://act1.xyz',
    category: 'AI Agent',
    tags: ['AI', 'Platform', 'Gaming'],
  },
  {
    name: 'AGENCY',
    description: 'AI Agent分析师',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/MWGI46DS2x.jpg',
    url: 'https://agency.xyz',
    category: 'AI Agent',
    tags: ['AI', 'Analytics'],
  },
  {
    name: 'AI16Z',
    description: '去中心化 AI 交易基金',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/W6ZeKgQRdk.jpg',
    url: 'https://ai16z.io',
    category: 'AI Agent',
    tags: ['AI', 'DeFi', 'DAO'],
  },
  {
    name: 'aiPool',
    description: 'AI Agent 自主发币',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/F19AmgM6e8.jpg',
    url: 'https://aipool.xyz',
    category: 'AI Agent',
    tags: ['AI', 'Token', 'Launchpad'],
  },
  {
    name: 'AIXBT',
    description: 'AI驱动的加密情报平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/7uW5FgJnKz.jpg',
    url: 'https://aixbt.xyz',
    category: 'AI Agent',
    tags: ['AI', 'Analytics', 'Trading'],
    hot: true,
  },
  {
    name: 'Alchemist AI',
    description: '无代码开发平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/4CE5stU04T.jpg',
    url: 'https://alchemistai.io',
    category: 'AI Agent',
    tags: ['AI', 'No-Code', 'Dev'],
  },
  {
    name: 'Anon',
    description: 'AI发币',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/H4jJ40xP7F.jpg',
    url: 'https://anon.ai',
    category: 'AI Agent',
    tags: ['AI', 'Token'],
  },
  {
    name: 'arc',
    description: 'AI框架',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/ppCnktr092.jpg',
    url: 'https://arc.dev',
    category: 'AI Agent',
    tags: ['AI', 'Framework'],
  },
  {
    name: 'AVA',
    description: '专注视觉与视频内容的跨平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/GnGi2IZJgu.jpg',
    url: 'https://ava.ai',
    category: 'AI Agent',
    tags: ['AI', 'Video', 'Content'],
  },
  {
    name: 'Clanker',
    description: 'AI驱动的Token Bot',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/yYLzdTNdRV.jpg',
    url: 'https://clanker.ai',
    category: 'AI Agent',
    tags: ['AI', 'Bot', 'Base'],
    hot: true,
  },
  {
    name: 'Cookie',
    description: 'AI Agent 索引平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/2N5v73HmIV.jpg',
    url: 'https://cookie.fun',
    category: 'AI Agent',
    tags: ['AI', 'Index', 'Platform'],
  },
  {
    name: 'Dolion',
    description: 'AI机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/B6T57zx9s7.jpg',
    url: 'https://dolion.ai',
    category: 'AI Agent',
    tags: ['AI', 'Bot'],
  },
  {
    name: 'DUNA',
    description: 'AI DAO',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/FaQyCytYO4.jpg',
    url: 'https://duna.io',
    category: 'AI Agent',
    tags: ['AI', 'DAO'],
  },
  {
    name: 'Eilza',
    description: '模块化AI 智能体框架',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/OM2IZji883.jpg',
    url: 'https://eilza.io',
    category: 'AI Agent',
    tags: ['AI', 'Framework', 'Modular'],
  },
  {
    name: 'Fartcoin',
    description: 'Terminal of Truths 上的首个MEME',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/v4RBqOP0Gd.jpg',
    url: 'https://fartcoin.io',
    category: 'AI Agent',
    tags: ['Meme', 'AI', 'Terminal of Truths'],
  },
  {
    name: 'G.A.M.E',
    description: '模块化的智能代理框架',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/nc7TgyhHmt.jpg',
    url: 'https://game.xyz',
    category: 'AI Agent',
    tags: ['AI', 'Framework', 'Modular'],
  },
  {
    name: 'Goatseus Maximus',
    description: 'AI概念MEME币',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/B4Byq0uPvP.jpg',
    url: 'https://goatseusmaximus.xyz',
    category: 'AI Agent',
    tags: ['Meme', 'AI', 'GOAT'],
  },
  {
    name: 'Griffain',
    description: 'AI 助手',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/ev5Ys78tz4.png',
    url: 'https://griffain.io',
    category: 'AI Agent',
    tags: ['AI', 'Assistant', 'Solana'],
  },
  {
    name: 'LEXICON',
    description: '开源AI Agent框架',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/1kGMNY0aPM.png',
    url: 'https://lexicon.ai',
    category: 'AI Agent',
    tags: ['AI', 'Framework', 'Open Source'],
  },
  {
    name: 'Luminous',
    description: 'AI自主协作的集体智慧',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/6givNu7d71.jpg',
    url: 'https://luminous.ai',
    category: 'AI Agent',
    tags: ['AI', 'Collective', 'Swarm'],
  },
  {
    name: 'Luna',
    description: 'AI 虚拟人',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/j55BJJq2XQ.jpg',
    url: 'https://luna.ai',
    category: 'AI Agent',
    tags: ['AI', 'Virtual', 'Avatar'],
  },
  {
    name: 'MAX',
    description: 'AI Agent Launchpad 平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/7TScMSm3vF.jpg',
    url: 'https://max.xyz',
    category: 'AI Agent',
    tags: ['AI', 'Launchpad'],
  },
  {
    name: 'Neur',
    description: 'AI 助手',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/AtKlwz874J.jpg',
    url: 'https://neur.ai',
    category: 'AI Agent',
    tags: ['AI', 'Assistant'],
  },
  {
    name: 'SPORE',
    description: '自主AI 进化平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/wRgD8F5xUD.jpg',
    url: 'https://spore.ai',
    category: 'AI Agent',
    tags: ['AI', 'Evolution', 'Platform'],
  },
  {
    name: 'SwarmNode.ai',
    description: '简化 AI Agent 部署',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/n4rb1v9gPj.jpg',
    url: 'https://swarmnode.ai',
    category: 'AI Agent',
    tags: ['AI', 'DevOps', 'Deployment'],
  },
  {
    name: 'swarms',
    description: 'AI框架',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/7cE8ulcHOj.jpg',
    url: 'https://swarms.world',
    category: 'AI Agent',
    tags: ['AI', 'Framework', 'Swarm'],
  },
  {
    name: 'The Hive',
    description: '基于AI Agent的DeFi项目',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/16EaKzhFT9.jpg',
    url: 'https://thehive.ai',
    category: 'AI Agent',
    tags: ['AI', 'DeFi'],
  },
  {
    name: 'VaderAI',
    description: '投资DAO 网络',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/qlN55YR2X8.jpg',
    url: 'https://vaderai.xyz',
    category: 'AI Agent',
    tags: ['AI', 'DAO', 'Investment'],
  },
  {
    name: 'Virtuals Protocol',
    description: 'AI Agent资产发行平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/EzYy3Vhbhr.jpg',
    url: 'https://virtuals.io',
    category: 'AI Agent',
    tags: ['AI', 'Gaming', 'Platform'],
    hot: true,
  },
  {
    name: 'vvaifu.fun',
    description: 'AI Agent 项目创建及发行平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/T5Va5F49y6.jpg',
    url: 'https://vvaifu.fun',
    category: 'AI Agent',
    tags: ['AI', 'Launchpad', 'Platform'],
  },
  {
    name: 'YNE',
    description: 'DeSci+AI Agent',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/GXXxl206JA.jpg',
    url: 'https://yne.io',
    category: 'AI Agent',
    tags: ['AI', 'DeSci', 'Research'],
  },
  {
    name: 'ZAILGO',
    description: 'AI框架',
    icon: 'https://cdn-img.panewslab.com/panews/2025/01/03/images/n4Vb492s9j.jpg',
    url: 'https://zailgo.ai',
    category: 'AI Agent',
    tags: ['AI', 'Framework'],
  },

  // ===== Meme常用工具 =====
  {
    name: 'pump.fun',
    description: 'Solana上Meme发布平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/7R3Rm09MW0.jpg',
    url: 'https://pump.fun',
    category: 'Meme工具',
    tags: ['Meme', 'Solana', 'Launchpad'],
    hot: true,
  },
  {
    name: 'Phantom',
    description: 'Sol链常用钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/gTh6JY9xPk.jpg',
    url: 'https://phantom.app',
    category: 'Meme工具',
    tags: ['Wallet', 'Solana'],
    hot: true,
  },
  {
    name: 'pump.news',
    description: 'MEME社交媒体雷达',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/31/images/x43OxtD7PB.png',
    url: 'https://pump.news',
    category: 'Meme工具',
    tags: ['Meme', 'Social', 'Analytics'],
  },
  {
    name: 'Cryptohunt',
    description: 'Web3智能投研平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/4GBlF72DoA.png',
    url: 'https://cryptohunt.net',
    category: 'Meme工具',
    tags: ['Research', 'AI', 'Analytics'],
  },
  {
    name: 'DEX Screener',
    description: 'Altcoin数据平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/md3f4v1ay5.jpg',
    url: 'https://dexscreener.com',
    category: 'Meme工具',
    tags: ['DEX', 'Charts', 'Multi-chain'],
    hot: true,
  },
  {
    name: 'Bubblemaps',
    description: '链上资产可视化平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/NkesvtgE96.png',
    url: 'https://bubblemaps.io',
    category: 'Meme工具',
    tags: ['Visualization', 'On-chain'],
  },
  {
    name: 'Birdeye',
    description: '链上交易数据聚合器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/6XOGGlxH7b.jpg',
    url: 'https://birdeye.so',
    category: 'Meme工具',
    tags: ['Data', 'Multi-chain', 'DEX'],
  },
  {
    name: 'DEXTools',
    description: 'DEX数据分析平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/6biHcNvbYK.jpg',
    url: 'https://www.dextools.io',
    category: 'Meme工具',
    tags: ['DEX', 'Trading', 'Charts'],
    hot: true,
  },
  {
    name: 'Ave.ai',
    description: '链上数据复制交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/X2D2BYiAuV.jpg',
    url: 'https://ave.ai',
    category: 'Meme工具',
    tags: ['Trading', 'Copy'],
  },
  {
    name: 'HolderScan',
    description: '筹码查询工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/MV0z89dzs4.jpg',
    url: 'https://holderscan.com',
    category: 'Meme工具',
    tags: ['Analytics', 'Holder'],
  },
  {
    name: 'Suiscan',
    description: 'Solana浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/k448lhrRYe.jpg',
    url: 'https://suiscan.xyz',
    category: 'Meme工具',
    tags: ['Explorer', 'Sui'],
  },
  {
    name: 'SolanaFM',
    description: 'Solana综合数据平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/Nb1rY17qX3.jpg',
    url: 'https://solana.fm',
    category: 'Meme工具',
    tags: ['Data', 'Solana'],
  },
  {
    name: 'Vybe Network',
    description: 'Solana 数据平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/Ry3gQ0Va8q.jpg',
    url: 'https://vybenetwork.xyz',
    category: 'Meme工具',
    tags: ['Data', 'Solana', 'Analytics'],
  },
  {
    name: 'Alphatrace',
    description: '链上资产分析工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/HkgfEf04no.png',
    url: 'https://alphatrace.io',
    category: 'Meme工具',
    tags: ['Analytics', 'On-chain'],
  },
  {
    name: 'Pepe Boost',
    description: 'Telegram交易机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/2Npbee65Cx.png',
    url: 'https://pepeboost.io',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Trading'],
  },
  {
    name: 'TweetScout',
    description: 'X活跃及社交评分工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/38FApzyOVh.png',
    url: 'https://tweetscout.io',
    category: 'Meme工具',
    tags: ['Twitter', 'Analytics', 'Social'],
  },
  {
    name: 'TwitterScore',
    description: 'X活跃及社交评分工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/Phpmd808j9.jpg',
    url: 'https://twitterscore.io',
    category: 'Meme工具',
    tags: ['Twitter', 'Analytics', 'Social'],
  },
  {
    name: 'Arkham',
    description: '钱包地址数据分析工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/4oWpR8q159.jpg',
    url: 'https://arkhamcrypto.com',
    category: 'Meme工具',
    tags: ['Analytics', 'Wallet', 'On-chain'],
    hot: true,
  },
  {
    name: 'GoPlus Security',
    description: '合约审计风险评估工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/aidHZ90qME.jpg',
    url: 'https://gopluslabs.io',
    category: 'Meme工具',
    tags: ['Security', 'Audit'],
  },
  {
    name: 'TokenSniffer',
    description: '代币合约风险检测工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/T4WzaWbBnh.jpg',
    url: 'https://tokensniffer.com',
    category: 'Meme工具',
    tags: ['Security', 'Token'],
  },
  {
    name: 'Honeypot.is',
    description: '蜜罐行为检测工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/6s3z3f6nG4.jpg',
    url: 'https://honeypot.is',
    category: 'Meme工具',
    tags: ['Security', 'Honeypot'],
  },
  {
    name: 'Rugcheck',
    description: '合约风险检测工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/apqi01427o.jpg',
    url: 'https://rugcheck.xyz',
    category: 'Meme工具',
    tags: ['Security', 'Audit'],
  },
  {
    name: 'Solsniffer',
    description: '合约风险检测工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/015T59Q6v0.png',
    url: 'https://solsniffer.com',
    category: 'Meme工具',
    tags: ['Security', 'Solana'],
  },
  {
    name: 'Zapper',
    description: '链上趋势查看工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/APcKcvuPGH.jpg',
    url: 'https://zapper.xyz',
    category: 'Meme工具',
    tags: ['DeFi', 'Portfolio', 'Multi-chain'],
  },
  {
    name: 'TrustWallet',
    description: '多链资产管理钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/Y7qK4EP3e7.jpg',
    url: 'https://trustwallet.com',
    category: 'Meme工具',
    tags: ['Wallet', 'Multi-chain'],
  },
  {
    name: 'OKXWallet',
    description: '多功能区块链钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/50hmi7nYf5.png',
    url: 'https://okx.com/web3',
    category: 'Meme工具',
    tags: ['Wallet', 'Multi-chain'],
  },
  {
    name: 'BullX',
    description: 'Web端交易工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/1l91VIp2uS.jpg',
    url: 'https://bullx.io',
    category: 'Meme工具',
    tags: ['Trading', 'Solana'],
  },
  {
    name: 'Jupiter',
    description: 'Solana DEX 聚合器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/3ZUu25mxJz.jpg',
    url: 'https://jup.ag',
    category: 'Meme工具',
    tags: ['DEX', 'Aggregator', 'Solana'],
  },
  {
    name: 'Raydium',
    description: 'Solana链上订单簿',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/4oR3qji9P5.jpg',
    url: 'https://raydium.io',
    category: 'Meme工具',
    tags: ['DEX', 'Solana', 'Order Book'],
  },
  {
    name: 'Hop',
    description: 'Sui链交易聚合器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/O3dVBZzikC.jpg',
    url: 'https://hop.ag',
    category: 'Meme工具',
    tags: ['Aggregator', 'Sui'],
  },
  {
    name: 'Cetus',
    description: 'Sui链DEX',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/pVOT29a8z1.png',
    url: 'https://cetus.zone',
    category: 'Meme工具',
    tags: ['DEX', 'Sui'],
  },
  {
    name: 'Turbos Finance',
    description: 'Sui上的Meme hub',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/3B1k108gQr.jpg',
    url: 'https://turbos.finance',
    category: 'Meme工具',
    tags: ['DEX', 'Sui', 'Meme'],
  },
  {
    name: 'DeepBook Protocol on Sui',
    description: 'Sui链上订单簿交易所',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/HJhAQvWQ7o.jpg',
    url: 'https://deepbook.sui',
    category: 'Meme工具',
    tags: ['DEX', 'Sui', 'Order Book'],
  },
  {
    name: 'BONKbot',
    description: '基于Solana的机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/kC553321Lu.jpg',
    url: 'https://bonkbot.com',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Solana'],
  },
  {
    name: 'Maestro',
    description: 'Telegram交易机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/a1Y00LC6Fy.jpg',
    url: 'https://maestro.bot',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Trading'],
  },
  {
    name: 'Trojan',
    description: 'Solana交易工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/7L59OUMAD2.jpg',
    url: 'https://trojan.exchange',
    category: 'Meme工具',
    tags: ['Trading', 'Solana', 'Bot'],
  },
  {
    name: 'Banana Gun',
    description: 'Telegram交易机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/Xm515R2F38.jpg',
    url: 'https://bananagun.io',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Trading'],
  },
  {
    name: 'SolTradingBot',
    description: 'Solana交易助手',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/t1lywG7zd2.jpg',
    url: 'https://soltradingbot.io',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Solana'],
  },
  {
    name: 'Unibot',
    description: 'Telegram交易工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/5l4KS799Al.jpg',
    url: 'https://unibot.app',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Trading'],
  },
  {
    name: 'SUIBABot',
    description: 'Sui上的交易机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/zdM4u2U3Pe.jpg',
    url: 'https://suibabot.io',
    category: 'Meme工具',
    tags: ['Bot', 'Telegram', 'Sui'],
  },
  {
    name: 'Move pump',
    description: 'Sui上Meme发布平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/3z1LKxBqgF.jpg',
    url: 'https://movepump.com',
    category: 'Meme工具',
    tags: ['Meme', 'Sui', 'Launchpad'],
  },
  {
    name: 'Logearn',
    description: 'AI抓金狗工具',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/D6T5Fqe281.jpg',
    url: 'https://logearn.io',
    category: 'Meme工具',
    tags: ['AI', 'Trading', 'Meme'],
  },
  {
    name: 'Dbotx',
    description: '全自动交易机器人',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/brnjvTJIy2.jpg',
    url: 'https://dbotx.io',
    category: 'Meme工具',
    tags: ['Bot', 'Auto Trading'],
  },
  {
    name: 'Photon',
    description: 'Sol链最快交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/10/18/images/i2773Wp921.jpg',
    url: 'https://photon-sol.com',
    category: 'Meme工具',
    tags: ['Trading', 'Solana'],
  },

  // ===== 区块浏览器 =====
  {
    name: 'Blockchair',
    description: '多链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/438TL42a0T.png',
    url: 'https://blockchair.com',
    category: '区块浏览器',
    tags: ['Explorer', 'Multi-chain', 'API'],
  },
  {
    name: 'Blockchain.com',
    description: '多链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/2V6xn8D363.png',
    url: 'https://www.blockchain.com/explorer',
    category: '区块浏览器',
    tags: ['Explorer', 'Multi-chain'],
  },
  {
    name: 'OKLINK',
    description: '多链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/08/23/images/25ynl9T4H7.png',
    url: 'https://www.oklink.com',
    category: '区块浏览器',
    tags: ['Explorer', 'Multi-chain'],
  },
  {
    name: 'Blockscout',
    description: 'EVM区块链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/1s5k08BBLk.png',
    url: 'https://blockscout.com',
    category: '区块浏览器',
    tags: ['Explorer', 'EVM', 'Open Source'],
  },
  {
    name: 'OP浏览器',
    description: 'Optimism浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/0H5saT45jL.jpg',
    url: 'https://optimistic.etherscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Optimism', 'Ethereum'],
  },
  {
    name: 'Arbiscan',
    description: 'Arbitrum浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/2Q3C65u1C3.png',
    url: 'https://arbiscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Arbitrum'],
  },
  {
    name: 'BscScan',
    description: 'BNB链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/jM2Sqtu71I.png',
    url: 'https://bscscan.com',
    category: '区块浏览器',
    tags: ['Explorer', 'BSC'],
  },
  {
    name: 'polygonscan',
    description: 'Polygon浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/XbHxFULZ3y.png',
    url: 'https://polygonscan.com',
    category: '区块浏览器',
    tags: ['Explorer', 'Polygon'],
  },
  {
    name: 'Solscan',
    description: 'Solana浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/Q542dSTP7n.png',
    url: 'https://solscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Solana'],
  },
  {
    name: 'Subscan',
    description: '波卡生态浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/XbjNHT7OEt.png',
    url: 'https://subscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Polkadot'],
  },
  {
    name: 'TRONSCAN',
    description: 'TRON浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/kDi9E5LE1s.png',
    url: 'https://tronscan.org',
    category: '区块浏览器',
    tags: ['Explorer', 'TRON'],
  },
  {
    name: 'AVASCAN',
    description: 'Avalanche浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/1fu3YGwbb0.png',
    url: 'https://snowtrace.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Avalanche'],
  },
  {
    name: 'FilScan',
    description: 'Filecoin浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/54ryz9lx9b.png',
    url: 'https://filscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Filecoin'],
  },
  {
    name: 'GnosisScan',
    description: 'Gnosis浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/t7T1U5CQxh.png',
    url: 'https://gnosisscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Gnosis'],
  },
  {
    name: 'NearScan',
    description: 'Near浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2022/08/30/images/BS46Xlp4nK.jpg',
    url: 'https://nearblocks.io',
    category: '区块浏览器',
    tags: ['Explorer', 'NEAR'],
  },
  {
    name: 'CronosScan',
    description: 'Cronos浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2022/08/30/images/45ahkwk4U9.jpg',
    url: 'https://cronoscan.com',
    category: '区块浏览器',
    tags: ['Explorer', 'Cronos'],
  },
  {
    name: 'MintScan',
    description: 'Cosmos浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2022/08/30/images/xQ91GAEjQ9.jpg',
    url: 'https://www.mintscan.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Cosmos'],
  },
  {
    name: 'Aptos',
    description: 'Aptos浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/26/images/Hy65xtM213.jpg',
    url: 'https://explorer.aptoslabs.com',
    category: '区块浏览器',
    tags: ['Explorer', 'Aptos'],
  },
  {
    name: 'Tokenview',
    description: '多链浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2022/12/27/images/41LAx9804Q.png',
    url: 'https://tokenview.io',
    category: '区块浏览器',
    tags: ['Explorer', 'Multi-chain'],
  },
  {
    name: 'Sui',
    description: 'Sui浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/195xcmxEGD.jpg',
    url: 'https://suiscan.xyz',
    category: '区块浏览器',
    tags: ['Explorer', 'Sui'],
  },

  // ===== 综合数据 =====
  {
    name: 'Glassnode',
    description: '全面的区块链链上数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/Kmpl43PkCD.png',
    url: 'https://glassnode.com',
    category: '综合数据',
    tags: ['Analytics', 'On-chain', 'Data'],
  },
  {
    name: 'Nansen',
    description: '资产链上活动追踪',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/VnR5EkO3i4.png',
    url: 'https://www.nansen.ai',
    category: '综合数据',
    tags: ['Analytics', 'On-chain', 'Wallet'],
  },
  {
    name: 'GeckoTerminal',
    description: '资产链上活动追踪',
    icon: 'https://cdn-img.panewslab.com/panews/2024/07/25/images/S2bPOiKXWz.jpg',
    url: 'https://www.geckoterminal.com',
    category: '综合数据',
    tags: ['DEX', 'Data', 'Charts'],
  },
  {
    name: 'Messari',
    description: '综合数据和报告平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/1M10zXS1p7.png',
    url: 'https://messari.io',
    category: '综合数据',
    tags: ['Research', 'Data', 'Reports'],
  },
  {
    name: 'Arkham',
    description: '链上数据分析平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/5Gm6xFLylY.png',
    url: 'https://arkhamcrypto.com',
    category: '综合数据',
    tags: ['Analytics', 'On-chain', 'Wallet'],
  },
  {
    name: 'CryptoHunt',
    description: '用AI发现阿尔法机会',
    icon: 'https://cdn-img.panewslab.com/panews/2024/08/23/images/6TInb70jA0.png',
    url: 'https://cryptohunt.net',
    category: '综合数据',
    tags: ['AI', 'Research', 'Analytics'],
  },
  {
    name: 'RootData',
    description: 'Web3资产数据平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/12/images/254ph0mU4c.png',
    url: 'https://www.rootdata.com',
    category: '综合数据',
    tags: ['Data', 'Analytics', 'Portfolio'],
  },
  {
    name: 'CryptoQuant',
    description: '综合链上交易数据指标',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/TPv5o4a6yH.png',
    url: 'https://cryptoquant.com',
    category: '综合数据',
    tags: ['Analytics', 'On-chain', 'Exchange'],
  },
  {
    name: 'L2BEAT',
    description: 'Layer2综合数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/eu5DC40U5Z.png',
    url: 'https://l2beat.com',
    category: '综合数据',
    tags: ['L2', 'Analytics', 'TVL'],
  },
  {
    name: 'Orbiter',
    description: 'Layer2综合数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/Li5vfqeQ24.png',
    url: 'https://orbiter.finance',
    category: '综合数据',
    tags: ['Bridge', 'Cross-chain', 'L2'],
  },
  {
    name: 'CryptoCompare',
    description: '加密市场数据即API',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/ed5AGjP98a.png',
    url: 'https://cryptocompare.com',
    category: '综合数据',
    tags: ['Data', 'API', 'Price'],
  },
  {
    name: 'Mytoken',
    description: '一站式数字资产行情资讯平台',
    icon: 'https://cdn-img.panewslab.com/panews/2025/03/21/images/64Tf7662e6.png',
    url: 'https://mytoken.io',
    category: '综合数据',
    tags: ['Data', 'News', 'Price'],
  },
  {
    name: 'Intotheblock',
    description: '综合数据指标和分析',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/VQH376slL0.png',
    url: 'https://intotheblock.com',
    category: '综合数据',
    tags: ['Analytics', 'AI', 'On-chain'],
  },
  {
    name: 'CryptoRank',
    description: 'ICO/IEO/IDO信息和回报率',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/o2ERRGOto3.png',
    url: 'https://cryptorank.io',
    category: '综合数据',
    tags: ['ICO', 'IEO', 'ROI'],
  },
  {
    name: 'santiment',
    description: '数据可视化平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/r80nw0jvJl.png',
    url: 'https://santiment.net',
    category: '综合数据',
    tags: ['Analytics', 'Social', 'On-chain'],
  },
  {
    name: 'Woobull',
    description: 'Woo的比特币指标',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/1CtbA7W2zv.png',
    url: 'https://woobull.com',
    category: '综合数据',
    tags: ['Bitcoin', 'Analytics', 'Metrics'],
  },
  {
    name: 'Ahr999',
    description: '9神比特币定投和抄底指标',
    icon: 'https://cdn-img.panewslab.com/panews/2022/09/05/images/0Da8z1RorE.png',
    url: 'https://www.aimyz.com',
    category: '综合数据',
    tags: ['Bitcoin', 'DCA', 'Index'],
  },
  {
    name: 'JieData',
    description: '链上异动地址锁定',
    icon: 'https://cdn-img.panewslab.com/panews/2022/12/09/images/2y6RAB14F6.png',
    url: 'https://jiedata.io',
    category: '综合数据',
    tags: ['Analytics', 'On-chain', 'Alert'],
  },
  {
    name: 'DexCheck',
    description: 'AI增强链上分析工具',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/53O7ozK9uV.jpg',
    url: 'https://dexcheck.io',
    category: '综合数据',
    tags: ['AI', 'DEX', 'Analytics'],
  },
  {
    name: 'DEX SCREENER',
    description: '可视化DEX聚合平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/8ijzi8v1gY.jpg',
    url: 'https://dexscreener.com',
    category: '综合数据',
    tags: ['DEX', 'Charts', 'Multi-chain'],
  },
  {
    name: 'bubblemaps',
    description: 'Token持仓分布',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/T1SP0w4q2q.jpg',
    url: 'https://bubblemaps.io',
    category: '综合数据',
    tags: ['Visualization', 'On-chain'],
  },
  {
    name: 'HONEYPOT',
    description: '貔貅项目检测',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/7Pl2Yf682l.jpg',
    url: 'https://honeypot.is',
    category: '综合数据',
    tags: ['Security', 'Honeypot'],
  },

  // ===== BTC生态工具 =====
  {
    name: 'Unisat',
    description: '钱包及交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/3HIEjdcYGf.jpg',
    url: 'https://unisat.io',
    category: 'BTC生态',
    tags: ['Wallet', 'Trading', 'BRC-20'],
  },
  {
    name: 'Xverse App',
    description: '钱包及交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/D729T2MwD9.jpg',
    url: 'https://xverse.app',
    category: 'BTC生态',
    tags: ['Wallet', 'Bitcoin', 'Ordinals'],
  },
  {
    name: 'Hiro Wallet',
    description: '比特币钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/1BWTa0jPh1.jpg',
    url: 'https://wallet.hiro.so',
    category: 'BTC生态',
    tags: ['Wallet', 'Stacks', 'Bitcoin'],
  },
  {
    name: 'Sparrow Wallet',
    description: '比特币钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/O3PWoxI387.jpg',
    url: 'https://sparrowwallet.com',
    category: 'BTC生态',
    tags: ['Wallet', 'Bitcoin'],
  },
  {
    name: 'Alby Wallet',
    description: '闪电网络专属钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/210Q74046Q.jpg',
    url: 'https://getalby.com',
    category: 'BTC生态',
    tags: ['Wallet', 'Lightning', 'Bitcoin'],
  },
  {
    name: 'OKX Web3 Wallet',
    description: '支持Ordinals协议多链钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/8eFhHRGi3e.jpg',
    url: 'https://okx.com/web3',
    category: 'BTC生态',
    tags: ['Wallet', 'Ordinals', 'Multi-chain'],
  },
  {
    name: 'Ordinals Wallet',
    description: 'Ordinals交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/Y4JHf8b6JQ.jpg',
    url: 'https://ordinalswallet.com',
    category: 'BTC生态',
    tags: ['Wallet', 'Ordinals', 'Bitcoin'],
  },
  {
    name: 'ME on BTC',
    description: 'Ordinals交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/iiBWKZbX4b.jpg',
    url: 'https://meonbitcoin.xyz',
    category: 'BTC生态',
    tags: ['Marketplace', 'Ordinals', 'Bitcoin'],
  },
  {
    name: 'IDclub',
    description: '铭文铸造、代打',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/i6f3H4ruW6.png',
    url: 'https://idclub.io',
    category: 'BTC生态',
    tags: ['Inscription', 'BRC-20', 'Service'],
  },
  {
    name: 'BestlnSlotXYZ',
    description: 'Ordinals 聚合交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/4acTsgEkuu.jpg',
    url: 'https://bestinslot.xyz',
    category: 'BTC生态',
    tags: ['Marketplace', 'Ordinals', 'Aggregator'],
  },
  {
    name: 'Mempool',
    description: 'BTC内存池及浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/kp0qgZxe2F.jpg',
    url: 'https://mempool.space',
    category: 'BTC生态',
    tags: ['Explorer', 'Bitcoin', 'Mempool'],
  },
  {
    name: 'Ordinal Explor',
    description: 'Ordinals 链上浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/pyy87Uw5m5.jpg',
    url: 'https://ordinals.com',
    category: 'BTC生态',
    tags: ['Explorer', 'Ordinals', 'Bitcoin'],
  },
  {
    name: 'BRC-20.io',
    description: 'BRC20代币数据',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/kxY5C38B3A.jpg',
    url: 'https://brc-20.io',
    category: 'BTC生态',
    tags: ['Data', 'BRC-20', 'Bitcoin'],
  },
  {
    name: 'TokenPocket',
    description: '多链钱包，支持Brc20',
    icon: 'https://cdn-img.panewslab.com/panews/2023/07/06/images/3IkpOh7C4N.png',
    url: 'https://tokenpocket.pro',
    category: 'BTC生态',
    tags: ['Wallet', 'Multi-chain', 'BRC-20'],
  },
  {
    name: 'GeniiData',
    description: '比特币生态工具网站',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/6V912a6H2p.png',
    url: 'https://geniidata.com',
    category: 'BTC生态',
    tags: ['Data', 'Bitcoin', 'Ordinals'],
  },
  {
    name: 'SatoSea',
    description: 'Ordinals服务平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/H7Uv5Gd0FF.png',
    url: 'https://satosea.io',
    category: 'BTC生态',
    tags: ['Marketplace', 'Ordinals', 'Bitcoin'],
  },
  {
    name: 'OrdinalsBot',
    description: '铸造蚀刻符文BOT',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/BK9P6A34sy.png',
    url: 'https://ordinalsbot.com',
    category: 'BTC生态',
    tags: ['Inscription', 'Bot', 'Bitcoin'],
  },
  {
    name: 'DotSwap',
    description: '比特币上原生DEX',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/Xi7Ck4WS80.png',
    url: 'https://dotswap.io',
    category: 'BTC生态',
    tags: ['DEX', 'Bitcoin', 'Runes'],
  },
  {
    name: 'Magic Eden',
    description: 'NFT交易市场',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/8nlve1B6up.png',
    url: 'https://magiceden.io',
    category: 'BTC生态',
    tags: ['NFT', 'Marketplace', 'Bitcoin'],
  },
  {
    name: 'Saturn',
    description: '比特币生态订单簿DEX',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/d21R5n455S.png',
    url: 'https://saturn.io',
    category: 'BTC生态',
    tags: ['DEX', 'Bitcoin', 'Order Book'],
  },
  {
    name: 'SatsX',
    description: 'ATOM和PIPE交易市场',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/0Rmq5OqVFb.jpg',
    url: 'https://satsx.io',
    category: 'BTC生态',
    tags: ['DEX', 'Bitcoin', 'Ordinals'],
  },
  {
    name: 'Rune Bitcoin',
    description: '符文Launchpad平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/7aM5z8TgRM.png',
    url: 'https://runebitcoin.xyz',
    category: 'BTC生态',
    tags: ['Runes', 'Launchpad', 'Bitcoin'],
  },
  {
    name: 'Meta Runes',
    description: '非托管符文Launchpad平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/H3JIFEFK1p.png',
    url: 'https://metarunes.xyz',
    category: 'BTC生态',
    tags: ['Runes', 'Launchpad', 'Bitcoin'],
  },
  {
    name: 'Ordbit',
    description: '符文Launchpad平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/U0WgvF2o9e.png',
    url: 'https://ordbit.com',
    category: 'BTC生态',
    tags: ['Runes', 'Launchpad', 'Bitcoin'],
  },
  {
    name: 'Liquidium',
    description: '比特币上P2P借贷协议',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/xJMX4qyD17.png',
    url: 'https://liquidium.fi',
    category: 'BTC生态',
    tags: ['Lending', 'Bitcoin', 'DeFi'],
  },
  {
    name: 'Runessance',
    description: '符文借贷平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/MH2own9519.png',
    url: 'https://runessance.io',
    category: 'BTC生态',
    tags: ['Lending', 'Runes', 'Bitcoin'],
  },
  {
    name: 'Runes Legacy',
    description: '符文项目看板',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/ibXtWDRRuA.png',
    url: 'https://runeslegacy.io',
    category: 'BTC生态',
    tags: ['Runes', 'Data', 'Bitcoin'],
  },
  {
    name: 'OrdiScan',
    description: 'BRC20区块浏览器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/80t6fs2w1Q.png',
    url: 'https://ordiscan.com',
    category: 'BTC生态',
    tags: ['Explorer', 'BRC-20', 'Bitcoin'],
  },
  {
    name: 'Ord.io',
    description: '铭文和符文市场',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/0VJf0jIWLQ.png',
    url: 'https://ord.io',
    category: 'BTC生态',
    tags: ['Marketplace', 'Ordinals', 'Runes'],
  },
  {
    name: 'RuneMine',
    description: 'Runes协议基础设施项目',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/5184f1EEst.png',
    url: 'https://runemine.xyz',
    category: 'BTC生态',
    tags: ['Runes', 'Infrastructure', 'Bitcoin'],
  },
  {
    name: 'BitX',
    description: '比特币上BRC20 DEX',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/29/images/eXvsUQ57Vb.png',
    url: 'https://bitx.exchange',
    category: 'BTC生态',
    tags: ['DEX', 'BRC-20', 'Bitcoin'],
  },

  // ===== CeFi =====
  {
    name: 'Datamish',
    description: '衍生品数据统计',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/J9U931OtBz.png',
    url: 'https://datamish.com',
    category: 'CeFi',
    tags: ['Futures', 'Data', 'Trading'],
  },
  {
    name: 'Coinglass',
    description: '衍生品数据统计',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/RHY50M8657.png',
    url: 'https://www.coinglass.com',
    category: 'CeFi',
    tags: ['Futures', 'Data', 'Liquidation'],
    hot: true,
  },
  {
    name: 'Bitfinex',
    description: '一周交易盈亏榜',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/eVVBljBV6b.png',
    url: 'https://www.bitfinex.com',
    category: 'CeFi',
    tags: ['Exchange', 'Trading', 'Data'],
  },
  {
    name: 'AICoin',
    description: '数据服务商',
    icon: 'https://cdn-img.panewslab.com/panews/2022/08/30/images/zMvGQ7w4Qp.jpg',
    url: 'https://www.aicoin.com',
    category: 'CeFi',
    tags: ['Data', 'Price', 'Trading'],
  },

  // ===== DeFi =====
  {
    name: 'DeFiPulse',
    description: '以太坊DeFi数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/9KgW6Dyj66.png',
    url: 'https://defipulse.com',
    category: 'DeFi',
    tags: ['DeFi', 'TVL', 'Ethereum'],
  },
  {
    name: 'DeFieye',
    description: '跨链桥比较',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/AN4Vrr82BI.png',
    url: 'https://defieye.io',
    category: 'DeFi',
    tags: ['Bridge', 'Cross-chain', 'Data'],
  },
  {
    name: 'revert',
    description: '跟踪无常损失和收益',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/H49tk0F9Lv.png',
    url: 'https://revert.finance',
    category: 'DeFi',
    tags: ['DeFi', 'IL', 'Analytics'],
  },
  {
    name: 'vfat',
    description: 'DeFi挖矿收益查询',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/J4ILJI7g17.png',
    url: 'https://vfat.tools',
    category: 'DeFi',
    tags: ['DeFi', 'Yield', 'Farming'],
  },
  {
    name: 'DeFi Rate',
    description: 'CeFi和DeFi平台存款和借贷利率',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/0a1HCWY6W2.png',
    url: 'https://defirate.com',
    category: 'DeFi',
    tags: ['DeFi', 'Rates', 'Lending'],
  },
  {
    name: 'Staking Rewards',
    description: '质押数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/0b41csS6jc.png',
    url: 'https://www.stakingrewards.com',
    category: 'DeFi',
    tags: ['Staking', 'Yield', 'Data'],
  },
  {
    name: 'RWA.XYZ',
    description: '真实世界资产项目数据',
    icon: 'https://cdn-img.panewslab.com/panews/2023/04/21/images/lU1xoZ7WKL.jpg',
    url: 'https://rwa.xyz',
    category: 'DeFi',
    tags: ['RWA', 'DeFi', 'Data'],
  },

  // ===== NFT =====
  {
    name: 'OpenSea',
    description: '最大的NFT交易平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/031EM3gg2l.png',
    url: 'https://opensea.io',
    category: 'NFT',
    tags: ['NFT', 'Marketplace'],
    hot: true,
  },
  {
    name: 'NFTSCAN',
    description: 'NFT浏览器和数据分析平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/49sal0F93V.png',
    url: 'https://nftscan.com',
    category: 'NFT',
    tags: ['NFT', 'Analytics', 'Explorer'],
  },
  {
    name: 'NFTGO',
    description: '排行、稀有度、巨鲸追踪等数据平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/shbbkqOsm1.png',
    url: 'https://nftgo.io',
    category: 'NFT',
    tags: ['NFT', 'Analytics', 'Rarity'],
  },
  {
    name: 'AlienSwap',
    description: 'NFT 市场和聚合器',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/10/images/Q81jmJPSYP.jpg',
    url: 'https://alienswap.finance',
    category: 'NFT',
    tags: ['NFT', 'Marketplace', 'Aggregator'],
  },
  {
    name: 'CryptoSlam',
    description: 'NFT数据聚合器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/NWufdh8W9r.png',
    url: 'https://cryptoslam.io',
    category: 'NFT',
    tags: ['NFT', 'Data', 'Sales'],
  },
  {
    name: 'NFTNerds',
    description: 'NFT交易信息',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/866f81HzaF.png',
    url: 'https://nftnerds.com',
    category: 'NFT',
    tags: ['NFT', 'Analytics', 'Trading'],
  },
  {
    name: 'Flips',
    description: 'NFT历史数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/eM32E7HYjM.png',
    url: 'https://flips.app',
    category: 'NFT',
    tags: ['NFT', 'History', 'Data'],
  },
  {
    name: 'NFTCalendar',
    description: 'NFT发行日历',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/X44d6DP6Kk.png',
    url: 'https://nftcalendar.io',
    category: 'NFT',
    tags: ['NFT', 'Calendar', 'Mint'],
  },
  {
    name: 'NFTTrack',
    description: '追踪NFT巨鲸',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/48O9xl28oL.png',
    url: 'https://nfttrack.io',
    category: 'NFT',
    tags: ['NFT', 'Whale', 'Tracking'],
  },
  {
    name: 'Degenmint',
    description: '铸造实时监控工具',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/11/images/QqWuiRv4Pk.jpg',
    url: 'https://degenmint.xyz',
    category: 'NFT',
    tags: ['NFT', 'Mint', 'Monitor'],
  },
  {
    name: 'Metasniper',
    description: 'NFT自动化Bot',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/11/images/gEd20YNBSD.jpg',
    url: 'https://metasniper.xyz',
    category: 'NFT',
    tags: ['NFT', 'Bot', 'Sniper'],
  },
  {
    name: 'Nftinspect',
    description: 'PFP推特用户实用度',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/11/images/9IXrj78Omo.jpg',
    url: 'https://nftinspect.io',
    category: 'NFT',
    tags: ['NFT', 'PFP', 'Twitter'],
  },

  // ===== DAO =====
  {
    name: 'Deep DAO',
    description: 'DAO相关数据统计',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/VS92OuBbxS.jpg',
    url: 'https://deepdao.io',
    category: 'DAO',
    tags: ['DAO', 'Data', 'Analytics'],
  },
  {
    name: 'Snapshot',
    description: '投票治理',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/549AzSwlV0.jpg',
    url: 'https://snapshot.org',
    category: 'DAO',
    tags: ['DAO', 'Voting', 'Governance'],
  },
  {
    name: 'Tally',
    description: '投票和治理分析',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/Ir8k3hP40G.jpg',
    url: 'https://www.tally.xyz',
    category: 'DAO',
    tags: ['DAO', 'Governance', 'Voting'],
  },
  {
    name: 'Juice Box',
    description: 'DAO融资',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/xZ1C58MEX0.jpg',
    url: 'https://juicebox.money',
    category: 'DAO',
    tags: ['DAO', 'Fundraising', 'Quadratic'],
  },
  {
    name: 'DaoHaus',
    description: '无代码启动DAO的平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/1WPQsFfn8E.jpg',
    url: 'https://daohaus.club',
    category: 'DAO',
    tags: ['DAO', 'No-code', 'Platform'],
  },
  {
    name: 'Syndicate',
    description: '创建投资型DAO',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/WK49HEXzo8.jpg',
    url: 'https://syndicate.io',
    category: 'DAO',
    tags: ['DAO', 'Investment', 'Protocol'],
  },

  // ===== DApp =====
  {
    name: 'DAppRadar',
    description: '综合类DApp数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/UfWm26PDjo.jpg',
    url: 'https://dappradar.com',
    category: 'DApp',
    tags: ['DApp', 'Data', 'Rankings'],
  },
  {
    name: 'Play to Earn',
    description: '链游排行',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/m7T6XCrHzK.jpg',
    url: 'https://playtoearn.net',
    category: 'DApp',
    tags: ['GameFi', 'P2E', 'Rankings'],
  },

  // ===== 空投 =====
  {
    name: 'Defi Llama',
    description: 'defillama',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/9m28cuE0DC.jpg',
    url: 'https://defillama.com/airdrops',
    category: '空投',
    tags: ['Airdrop', 'DeFi', 'Data'],
  },
  {
    name: 'Earnfi',
    description: '个人地址空投查询',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/VGy7356eDN.jpg',
    url: 'https://earnfi.com',
    category: '空投',
    tags: ['Airdrop', 'Portfolio', 'Tracker'],
  },
  {
    name: 'DropsEarn',
    description: '完成任务瓜分空投',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/N304y380gu.jpg',
    url: 'https://dropsearn.com',
    category: '空投',
    tags: ['Airdrop', 'Quest', 'Rewards'],
  },
  {
    name: 'TaskOn',
    description: '营销运营任务协作平台',
    icon: 'https://cdn-img.panewslab.com/panews/2023/02/15/images/26lyrc0ED0.jpg',
    url: 'https://taskon.xyz',
    category: '空投',
    tags: ['Quest', 'Airdrop', 'Campaign'],
  },

  // ===== 矿业 =====
  {
    name: 'BitInfoCharts',
    description: '挖矿难度/巨鲸排行等综合数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/5HRd8pX5Pj.jpg',
    url: 'https://bitinfocharts.com',
    category: '矿业',
    tags: ['Mining', 'Data', 'Bitcoin'],
  },
  {
    name: 'Coin Dance',
    description: '综合比特币数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/G1piT9xbIV.jpg',
    url: 'https://coin.dance',
    category: '矿业',
    tags: ['Bitcoin', 'Data', 'Mining'],
  },
  {
    name: 'f2pool',
    description: '比特币矿池、矿机数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/2y00FU2bK7.jpg',
    url: 'https://f2pool.io',
    category: '矿业',
    tags: ['Mining', 'Pool', 'Bitcoin'],
  },
  {
    name: 'CBECI',
    description: '比特币电力消耗统计',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/rCX2tD1k42.jpg',
    url: 'https://cbeci.org',
    category: '矿业',
    tags: ['Bitcoin', 'Energy', 'ESG'],
  },
  {
    name: 'Digicomomist',
    description: '比特币能源消耗数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/528865fKkF.jpg',
    url: 'https://digiconomist.net',
    category: '矿业',
    tags: ['Bitcoin', 'Energy', 'Carbon'],
  },
  {
    name: '1ML',
    description: '比特币闪电网络数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/y30I4KxZ9o.jpg',
    url: 'https://1ml.com',
    category: '矿业',
    tags: ['Bitcoin', 'Lightning', 'Network'],
  },
  {
    name: 'BitcoinVisuals',
    description: '比特币闪电网络数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/Fap6XNoLo2.jpg',
    url: 'https://bitcoinvisuals.com',
    category: '矿业',
    tags: ['Bitcoin', 'Lightning', 'Visualization'],
  },
  {
    name: '51%攻击',
    description: '51攻击花费数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/LvmnF6sX85.jpg',
    url: 'https://crypto51.app',
    category: '矿业',
    tags: ['Mining', 'Security', '51 Attack'],
  },
  {
    name: 'BitNodes',
    description: '比特币节点数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/oNonK00950.jpg',
    url: 'https://bitnodes.io',
    category: '矿业',
    tags: ['Bitcoin', 'Node', 'Network'],
  },

  // ===== 钱包和授权管理 =====
  {
    name: 'Ledger',
    description: '硬件钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/p0ob6JeWSg.jpg',
    url: 'https://www.ledger.com',
    category: '钱包工具',
    tags: ['Wallet', 'Hardware', 'Security'],
  },
  {
    name: 'Trezor',
    description: '硬件钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/81n3o9HDW0.jpg',
    url: 'https://trezor.io',
    category: '钱包工具',
    tags: ['Wallet', 'Hardware', 'Security'],
  },
  {
    name: 'imKey',
    description: '硬件钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2022/11/03/images/218VT77t1D.jpg',
    url: 'https://imkey.im',
    category: '钱包工具',
    tags: ['Wallet', 'Hardware'],
  },
  {
    name: 'OneKey',
    description: '全开源硬件钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/09/images/S54t8kg5oF.png',
    url: 'https://onekey.so',
    category: '钱包工具',
    tags: ['Wallet', 'Hardware', 'Open Source'],
  },
  {
    name: 'KeyPal',
    description: '双芯片硬件钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2022/10/10/images/LSG2fa30O2.png',
    url: 'https://keypal.pro',
    category: '钱包工具',
    tags: ['Wallet', 'Hardware'],
  },
  {
    name: 'ethos',
    description: 'Sui生态钱包',
    icon: 'https://cdn-img.panewslab.com/panews/2023/05/06/images/598TApeGDh.jpg',
    url: 'https://ethoswallet.xyz',
    category: '钱包工具',
    tags: ['Wallet', 'Sui'],
  },
  {
    name: 'DeBank',
    description: '资产查看和管理',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/m2Z46O6191.jpg',
    url: 'https://debank.com',
    category: '钱包工具',
    tags: ['Portfolio', 'DeFi', 'Wallet'],
  },
  {
    name: 'Zapper',
    description: '资产查看和管理',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/cPJkf60OhW.jpg',
    url: 'https://zapper.xyz',
    category: '钱包工具',
    tags: ['Portfolio', 'DeFi', 'Multi-chain'],
  },
  {
    name: 'Zerion',
    description: '资产查看和管理',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/qw1hHVAzA2.jpg',
    url: 'https://zerion.io',
    category: '钱包工具',
    tags: ['Portfolio', 'DeFi', 'Multi-chain'],
  },
  {
    name: 'Revoke',
    description: '授权检查',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/7haG8cpat7.jpg',
    url: 'https://revoke.cash',
    category: '钱包工具',
    tags: ['Security', 'Approval', 'Wallet'],
  },

  // ===== 其他 =====
  {
    name: 'Umy.com',
    description: '基于Web3的旅行平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/03/images/j83k2IbPfj.png',
    url: 'https://umy.com',
    category: '其他',
    tags: ['Travel', 'Web3', 'Lifestyle'],
  },
  {
    name: 'Secure3',
    description: '智能竞赛安全审计平台',
    icon: 'https://cdn-img.panewslab.com/panews/2024/04/03/images/xr0Lw658fE.png',
    url: 'https://secure3.io',
    category: '其他',
    tags: ['Security', 'Audit', 'Contest'],
  },
  {
    name: 'Bit Jungle',
    description: '领先的区块链安全公司',
    icon: 'https://cdn-img.panewslab.com/panews/2023/08/23/images/kpYYcoh3e1.png',
    url: 'https://bitjungle.io',
    category: '其他',
    tags: ['Security', 'Audit'],
  },
  {
    name: 'Blocknative',
    description: 'Gas和MemPool数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/rfvmUI2st3.jpg',
    url: 'https://blocknative.com',
    category: '其他',
    tags: ['Gas', 'Mempool', 'Data'],
  },
  {
    name: 'Ultra Sound',
    description: '以太坊销毁数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/15DpHRM1Yg.jpg',
    url: 'https://ultrasound.money',
    category: '其他',
    tags: ['Ethereum', 'Burn', 'Analytics'],
  },
  {
    name: 'MEV-Explore',
    description: '以太坊上MEV活动查询',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/PMJtvj7IHE.jpg',
    url: 'https://explore.mev.xyz',
    category: '其他',
    tags: ['MEV', 'Ethereum', 'Analytics'],
  },
  {
    name: 'Token Terminal',
    description: '协议收入指标',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/D8gpFAvJ0f.jpg',
    url: 'https://tokenterminal.io',
    category: '其他',
    tags: ['Revenue', 'DeFi', 'Analytics'],
  },
  {
    name: 'Crypto Fees',
    description: '加密项目费用',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/3Y7yca38w5.jpg',
    url: 'https://cryptofees.info',
    category: '其他',
    tags: ['Fees', 'Revenue', 'Data'],
  },
  {
    name: 'dcaBTC',
    description: '比特币投资、定投计算器',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/NALAu4q5e3.jpg',
    url: 'https://dcabtc.com',
    category: '其他',
    tags: ['Bitcoin', 'DCA', 'Calculator'],
  },
  {
    name: 'Bitcoinity',
    description: '比特币交易数据',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/7C5x1P7zsB.jpg',
    url: 'https://bitcoinity.org',
    category: '其他',
    tags: ['Bitcoin', 'Data', 'Markets'],
  },
  {
    name: 'Chain Broker',
    description: '融资信息/VC回报率和排名',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/vHSMWABDBx.jpg',
    url: 'https://chainbroker.io',
    category: '其他',
    tags: ['VC', 'Fundraising', 'Data'],
  },
  {
    name: 'Dove Metrics',
    description: '融资信息汇总',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/2wh6HdWqKl.jpg',
    url: 'https://dovemetrics.com',
    category: '其他',
    tags: ['Fundraising', 'Data', 'Analytics'],
  },
  {
    name: 'ICO Analytics',
    description: '提供ICO日历',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/7N6ihf9hwe.jpg',
    url: 'https://icoanalytics.io',
    category: '其他',
    tags: ['ICO', 'Calendar', 'Data'],
  },
  {
    name: 'Infinite Market Cap',
    description: '加密货币和传统资产的市值排名',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/27y6l5zic5.jpg',
    url: 'https://infinite.marketcap',
    category: '其他',
    tags: ['Market Cap', 'Comparison', 'Data'],
  },
  {
    name: 'LunarCrush',
    description: '社交媒体加密信息监测',
    icon: 'https://cdn-img.panewslab.com/panews/2024/12/26/images/FJB5A8VPW3.jpg',
    url: 'https://lunarcrush.com',
    category: '其他',
    tags: ['Social', 'Analytics', 'Sentiment'],
  },
  {
    name: 'TokenUnlocks',
    description: '知名项目代币解锁数据',
    icon: 'https://cdn-img.panewslab.com/panews/2022/11/04/images/y5w1gO6w7f.jpg',
    url: 'https://tokenunlocks.app',
    category: '其他',
    tags: ['Token', 'Unlock', 'Vesting'],
  },
];

console.log(`Total PANews tools: ${panewsTools.length}`);
